---
name: Perl-Critic-Dynamic
version: 0.04
author:
  - 'Jeffrey Thalhammer <thaljef@cpan.org>'
abstract: Dynamic policies for Perl::Critic
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Devel::Symdump: 2.07
  Perl::Critic::Policy: 1.053
  Perl::Critic::Utils: 1.053
  Readonly: 0
  Storable: 2.16
build_requires:
  Test::More: 0
provides:
  Perl::Critic::Dynamic:
    file: lib/Perl/Critic/Dynamic.pm
    version: 0.04
  Perl::Critic::DynamicPolicy:
    file: lib/Perl/Critic/DynamicPolicy.pm
    version: 0.03
  Perl::Critic::Policy::Dynamic::ValidateAgainstSymbolTable:
    file: lib/Perl/Critic/Policy/Dynamic/ValidateAgainstSymbolTable.pm
    version: 0.04
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
